### ISSUE TITLE
drop orientdb-connectors

### ISSUE THREAD

**Issue by laglangyue** [apache/pekko-connectors#591]
I notice that akka drop it.
and Reason is :
- product is dead ,website is closed.
- So we should drop it.

**Comment by pjfanning** [comment]
Please provide evidence - like links.

https://github.com/orientechnologies/orientdb has no apparent mention of the project being unmaintained.

**Comment by laglangyue** [comment]
It seems that the commercial maintenance of orientdb is not active, and all open source has been given to the community. Alpakka misunderstood.
the websit transfer  `https://orientdb.org/`
https://orientdb.dev/
