### ISSUE TITLE
Integrate AWS SPI into pekko-connectors

### ISSUE THREAD

**Issue by mdedetrich** [apache/pekko-connectors#612]
Since aws-spi-pekko-http has [cleared ip clearance](https://lists.apache.org/thread/cd5tpkjlqkt416749kl8l9mbbztkmmx5) This issue is to track integrating https://github.com/pjfanning/aws-spi-pekko-http into pekko-connectors .

I will take this on after https://github.com/apache/pekko-connectors/pull/588 is merged

**Comment by pjfanning** [comment]
Marking as blocked because we do not yet have an iCLA from @matsluni

**Comment by pjfanning** [comment]
Thanks @matsluni for providing the iCLA. This issue is now ready for uptake.

**Comment by pjfanning** [comment]
@mdedetrich I created #648
