### ISSUE TITLE
splitWhen use case that might need a pekko 1.1 change

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko-connectors#737]
splitWhen/splitAfter have been changed in Pekko 1.1

see https://github.com/playframework/playframework/pull/12793

https://github.com/apache/pekko-connectors/blob/97e0b0813f4c3e759d98cd4a31eaaef2931729e3/s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/SplitAfterSize.scala#L42

https://github.com/apache/pekko-connectors/blob/97e0b0813f4c3e759d98cd4a31eaaef2931729e3/s3/src/main/scala/org/apache/pekko/stream/connectors/s3/impl/SplitAfterSizeWithContext.scala#L38

**Comment by pjfanning** [comment]
@He-Pin @mdedetrich There are no test failures but it appears that the behaviour change in splitWhen may be affecting the Play Framework and may also affect our S3 connector.

**Comment by mdedetrich** [comment]
> @He-Pin @mdedetrich There are no test failures but it appears that the behaviour change in splitWhen may be affecting the Play Framework and may also affect our S3 connector.

For S3 its a non issue (I already checked), with Play I cannot comment so its probably best we explicitly notify them to avoid any suprirses.
